select * from event_experiment; 
select * from tb_address;
select * from tb_email;
select * from tb_person;
select * from tb_phone;
select * from tb_user_1; 


-- FUNCTION ONE FOR PROJECT

-- MAIN QUERY FOR FUNCTION ONE
select person_id, count(pho_number) TOTAL from tb_phone HAVING PERSON_ID = 544 group by person_id;

-- CREATE FUNCTION 1: TO GET NUMBER OF PHONES NUMBER BASED ON PERSON_ID
CREATE OR REPLACE
FUNCTION PHONE_NUMBERS
  (PERSONID IN NUMBER)
  RETURN NUMBER
  IS
  PHONENUM NUMBER(10,2);
BEGIN
  --FOR OBJ IN (SELECT *  FROM TB_PHONE where PERSON_ID = PERSONID) LOOP  
    FOR OBJ IN (select person_id, count(pho_number) TOTAL from tb_phone HAVING PERSON_ID = 544 group by person_id) LOOP 
    --dbms_output.put_line('PHONE NUMBER=' || OBJ.PHO_NUMBER);
    PHONENUM := OBJ.TOTAL;
     END LOOP;
  RETURN PHONENUM;
END;

-- RUNNING FUNCTION THROUGH ANONYMOUS BLOCK
-- ENTER PERSON_ID TO GET THE NUMBER OF PHONE NUMBERS THE PERSON HAS
DECLARE
  RETURNVALUE NUMBER(10,2);
BEGIN
  RETURNVALUE := PHONE_NUMBERS(544);
  DBMS_OUTPUT.PUT_LINE(RETURNVALUE);
END;


-- FUNCTION TWO FOR PROJECT
select count(person_id) TOTAL from tb_PERSON;

-- CREATE FUNCTION 2: TO GET NUMBER OF PEOPLE IN THE TB_PERSON TABLE
CREATE OR REPLACE
FUNCTION PERSON_TOTAL
  --(PERSONTOT OUT NUMBER)
  RETURN NUMBER
  IS
  PERSONTOT NUMBER(10,2);
BEGIN
    FOR OBJ IN (select count(person_id) TOTAL from tb_PERSON) LOOP 
    PERSONTOT:= OBJ.TOTAL;
     END LOOP;
  RETURN PERSONTOT;
END;


-- RUNNING FUNCTION THROUGH ANONYMOUS BLOCK
-- GET THE TOTAL NUMBER OF PEOPLE IN TB_PERSON TABLE
DECLARE
  RETURNVALUE NUMBER(10,2);
BEGIN
  RETURNVALUE := PERSON_TOTAL;
  DBMS_OUTPUT.PUT_LINE(RETURNVALUE);
END;







